### ISSUE TITLE
Russian characters in names are not supported

### ISSUE THREAD

**Issue by nick4fake** [acenko/FLACCue#3]
/var/log/packages/FLACCue.log:
```
Traceback (most recent call last):
  File "/volume1/@appstore/FLACCue/usr/bin/fuse.py", line 498, in _wrapper
    return func(*args, **kwargs) or 0
  File "/volume1/@appstore/FLACCue/usr/bin/fuse.py", line 708, in readdir
    if filler(buf, name.encode(self.encoding), st, offset) != 0:
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd0' in position 0: surrogates not allowed
```

**Comment by nick4fake** [comment]
https://github.com/acenko/FLACCue/blob/master/synology_package/FLACCue/fuse.py#L708

**Comment by nick4fake** [comment]
@acenko I've created PR with fix
